<img src="http://www.digitalvidya.com/wp-content/uploads/2013/05/logoa5-300x95.png">

## Data Analysis using Python Assignment
### Digital Vidya Copyright

#### Download the IPL dataset from the given link and load it in a dataframe using the following command.
#### This dataset contains details of each match played in IPL from season 2008 to 2016. Each row represents one match.
#### Answer the questions based on the dataset. 
#### Please show the code you would use to get to the answer.

In [33]:
import pandas as pd
import numpy as np
import datetime as dt

In [7]:
matches = pd.read_csv('matches.csv') #<location/filename.csv>

matches.shape

(577, 18)

In [11]:

# 1. What is the easiest way to view the details of the last match of the dataset?
matches.tail(1)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
576,577,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [14]:
# 2. Create a slice of this dataframe to only show the details from index 517 to 576 and columns id, season, city 
#and date. Print the output.
df = matches[517:576]
df_show = df[['id','season','city','date']]
df_show

      id  season           city        date
517  518    2016         Mumbai  2016-04-09
518  519    2016        Kolkata  2016-04-10
519  520    2016     Chandigarh  2016-04-11
520  521    2016      Bangalore  2016-04-12
521  522    2016        Kolkata  2016-04-13
522  523    2016         Rajkot  2016-04-14
523  524    2016          Delhi  2016-04-15
524  525    2016      Hyderabad  2016-04-16
525  526    2016         Mumbai  2016-04-16
526  527    2016     Chandigarh  2016-04-17
527  528    2016      Bangalore  2016-04-17
528  529    2016      Hyderabad  2016-04-18
529  530    2016     Chandigarh  2016-04-19
530  531    2016         Mumbai  2016-04-20
531  532    2016         Rajkot  2016-04-21
532  533    2016           Pune  2016-04-22
533  534    2016          Delhi  2016-04-23
534  535    2016      Hyderabad  2016-04-23
535  536    2016         Rajkot  2016-04-24
536  537    2016           Pune  2016-04-24
537  538    2016     Chandigarh  2016-04-25
538  539    2016      Hyderabad  2016-04-26
539  540    2016          Delhi  2016-04-27
540  541    2016         Mumbai  2016-04-28
541  542    2016           Pune  2016-04-29
542  543    2016          Delhi  2016-04-30
543  544    2016      Hyderabad  2016-04-30
544  545    2016         Rajkot  2016-05-01
545  546    2016           Pune  2016-05-01
546  547    2016      Bangalore  2016-05-02
547  548    2016         Rajkot  2016-05-03
548  549    2016        Kolkata  2016-05-04
549  550    2016          Delhi  2016-05-05
550  551    2016      Hyderabad  2016-05-06
551  552    2016      Bangalore  2016-05-07
552  553    2016     Chandigarh  2016-05-07
553  554    2016  Visakhapatnam  2016-05-08
554  555    2016        Kolkata  2016-05-08
555  556    2016     Chandigarh  2016-05-09
556  557    2016  Visakhapatnam  2016-05-10
557  558    2016      Bangalore  2016-05-11
558  559    2016      Hyderabad  2016-05-12
559  560    2016  Visakhapatnam  2016-05-13
560  561    2016      Bangalore  2016-05-14
561  562    2016        Kolkata  2016-05-14
562  563    2016     Chandigarh  2016-05-15
563  564    2016  Visakhapatnam  2016-05-15
564  565    2016        Kolkata  2016-05-16
565  566    2016  Visakhapatnam  2016-05-17
566  567    2016      Bangalore  2016-05-18
567  568    2016         Kanpur  2016-05-19
568  569    2016         Raipur  2016-05-20
569  570    2016  Visakhapatnam  2016-05-21
570  571    2016         Kanpur  2016-05-21
571  572    2016        Kolkata  2016-05-22
572  573    2016         Raipur  2016-05-22
573  574    2016      Bangalore  2016-05-24
574  575    2016          Delhi  2016-05-25
575  576    2016          Delhi  2016-05-27

In [20]:
# 3. The final match of the season 2011 is at the index 247, on what date was the match played?

df_value = matches[matches.index == 247]
print(df_value['date'])

247    2011-05-28
Name: date, dtype: object

In [26]:
# 4. Create a new dataframe called matches_compact which contains only the id, season, date and winner. 
#What is the shape of the matches_compact?

matches_compact = pd.DataFrame(matches)
matches_compact = matches_compact[['id','season','date','winner']]
matches_compact.shape

(577, 4)

In [51]:
# 5. How many matches were played in the year 2010? 


matches_2010 = matches[matches.season == 2010]
matches_2010.id.count()

60

In [97]:
# 6. How will you find the highest margin of runs by which any team won the match in matches so far? 
#Which team was it and by how many runs did it win?

df = pd.DataFrame(matches)
matches_margin = matches['win_by_runs'].max()
matches_margin_name = matches[matches.win_by_runs == matches_margin]
print(matches_margin)
print(matches_margin_name.team1)

144
560    Royal Challengers Bangalore
Name: team1, dtype: object

In [63]:
# 7. Here is a dictionary of short names for all the team names in the dataset. Create a new dataframe called 
# matches_alias by replacing names in all the columns with long team names.
team_names = {'Kolkata Knight Riders': 'KKR', 
              'Chennai Super Kings': 'CSK', 
              'Rajasthan Royals' : 'RR',
               'Mumbai Indians' : 'MI', 
              'Deccan Chargers' : 'DC', 
              'Kings XI Punjab' : 'KIXP',
               'Royal Challengers Bangalore' : 'RCB', 
              'Delhi Daredevils' : 'DD',
              'Kochi Tuskers Kerala' : 'KTK', 
              'Pune Warriors' : 'PW', 
              'Sunrisers Hyderabad' : 'SRH',
              'Rising Pune Supergiants' : 'RPS', 
              'Gujarat Lions' : 'GL'}

matches_alias = matches.replace(team_names)
matches_alias

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2008,Bangalore,2008-04-18,KKR,RCB,RCB,field,normal,0,KKR,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,NaN
1,2,2008,Chandigarh,2008-04-19,CSK,KIXP,CSK,bat,normal,0,CSK,33,0,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",MR Benson,SL Shastri,NaN
2,3,2008,Delhi,2008-04-19,RR,DD,RR,bat,normal,0,DD,0,9,MF Maharoof,Feroz Shah Kotla,Aleem Dar,GA Pratapkumar,NaN
3,4,2008,Mumbai,2008-04-20,MI,RCB,MI,bat,normal,0,RCB,0,5,MV Boucher,Wankhede Stadium,SJ Davis,DJ Harper,NaN
4,5,2008,Kolkata,2008-04-20,DC,KKR,DC,bat,normal,0,KKR,0,5,DJ Hussey,Eden Gardens,BF Bowden,K Hariharan,NaN
5,6,2008,Jaipur,2008-04-21,KIXP,RR,KIXP,bat,normal,0,RR,0,6,SR Watson,Sawai Mansingh Stadium,Aleem Dar,RB Tiffin,NaN
6,7,2008,Hyderabad,2008-04-22,DC,DD,DC,bat,normal,0,DD,0,9,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",IL Howell,AM Saheba,NaN
7,8,2008,Chennai,2008-04-23,CSK,MI,MI,field,normal,0,CSK,6,0,ML Hayden,"MA Chidambaram Stadium, Chepauk",DJ Harper,GA Pratapkumar,NaN
8,9,2008,Hyderabad,2008-04-24,DC,RR,RR,field,normal,0,RR,0,3,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,MR Benson,NaN
9,10,2008,Chandigarh,2008-04-25,KIXP,MI,MI,field,normal,0,KIXP,66,0,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Aleem Dar,AM Saheba,NaN
10,11,2008,Bangalore,2008-04-26,RCB,RR,RR,field,normal,0,RR,0,7,SR Watson,M Chinnaswamy Stadium,MR Benson,IL Howell,NaN
11,12,2008,Chennai,2008-04-26,KKR,CSK,KKR,bat,normal,0,CSK,0,9,JDP Oram,"MA Chidambaram Stadium, Chepauk",BF Bowden,AV Jayaprakash,NaN
12,13,2008,Mumbai,2008-04-27,MI,DC,DC,field,normal,0,DC,0,10,AC Gilchrist,Dr DY Patil Sports Academy,Asad Rauf,SL Shastri,NaN
13,14,2008,Chandigarh,2008-04-27,DD,KIXP,DD,bat,normal,0,KIXP,0,4,SM Katich,"Punjab Cricket Association Stadium, Mohali",RE Koertzen,I Shivram,NaN
14,15,2008,Bangalore,2008-04-28,CSK,RCB,CSK,bat,normal,0,CSK,13,0,MS Dhoni,M Chinnaswamy Stadium,BR Doctrove,RB Tiffin,NaN
15,16,2008,Kolkata,2008-04-29,KKR,MI,KKR,bat,normal,0,MI,0,7,ST Jayasuriya,Eden Gardens,BF Bowden,AV Jayaprakash,NaN
16,17,2008,Delhi,2008-04-30,DD,RCB,RCB,field,normal,0,DD,10,0,GD McGrath,Feroz Shah Kotla,Aleem Dar,I Shivram,NaN
17,18,2008,Hyderabad,2008-05-01,DC,KIXP,KIXP,field,normal,0,KIXP,0,7,SE Marsh,"Rajiv Gandhi International Stadium, Uppal",BR Doctrove,RB Tiffin,NaN
18,19,2008,Jaipur,2008-05-01,RR,KKR,RR,bat,normal,0,RR,45,0,SA Asnodkar,Sawai Mansingh Stadium,RE Koertzen,GA Pratapkumar,NaN
19,20,2008,Chennai,2008-05-02,CSK,DD,CSK,bat,normal,0,DD,0,8,V Sehwag,"MA Chidambaram Stadium, Chepauk",BF Bowden,K Hariharan,NaN
20,21,2008,Hyderabad,2008-05-25,DC,RCB,DC,bat,normal,0,RCB,0,5,R Vinay Kumar,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,RE Koertzen,NaN
21,22,2008,Chandigarh,2008-05-03,KIXP,KKR,KIXP,bat,normal,0,KIXP,9,0,IK Pathan,"Punjab Cricket Association Stadium, Mohali",DJ Harper,I Shivram,NaN
22,23,2008,Mumbai,2008-05-04,MI,DD,DD,field,normal,0,MI,29,0,SM Pollock,Dr DY Patil Sports Academy,IL Howell,RE Koertzen,NaN
23,24,2008,Jaipur,2008-05-04,CSK,RR,CSK,bat,normal,0,RR,0,8,Sohail Tanvir,Sawai Mansingh Stadium,Asad Rauf,AV Jayaprakash,NaN
24,25,2008,Bangalore,2008-05-05,RCB,KIXP,KIXP,field,normal,0,KIXP,0,6,S Sreesanth,M Chinnaswamy Stadium,SJ Davis,BR Doctrove,NaN
25,26,2008,Chennai,2008-05-06,CSK,DC,DC,field,normal,0,DC,0,7,AC Gilchrist,"MA Chidambaram Stadium, Chepauk",MR Benson,RB Tiffin,NaN
26,27,2008,Mumbai,2008-05-07,RR,MI,MI,field,normal,0,MI,0,7,A Nehra,Dr DY Patil Sports Academy,DJ Harper,RE Koertzen,NaN
27,28,2008,Delhi,2008-05-08,DD,CSK,CSK,field,normal,0,CSK,0,4,MS Dhoni,Feroz Shah Kotla,Aleem Dar,RB Tiffin,NaN
28,29,2008,Kolkata,2008-05-08,KKR,RCB,KKR,bat,normal,0,KKR,5,0,SC Ganguly,Eden Gardens,Asad Rauf,IL Howell,NaN
29,30,2008,Jaipur,2008-05-09,DC,RR,RR,field,normal,0,RR,0,8,YK Pathan,Sawai Mansingh Stadium,MR Benson,AM Saheba,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,548,2016,Rajkot,2016-05-03,GL,DD,DD,field,normal,0,DD,0,8,RR Pant,Saurashtra Cricket Association Stadium,CB Gaffaney,BNJ Oxenford,NaN
548,549,2016,Kolkata,2016-05-04,KKR,KIXP,KIXP,field,normal,0,KKR,7,0,AD Russell,Eden Gardens,AK Chaudhary,HDPK Dharmasena,NaN
549,550,2016,Delhi,2016-05-05,DD,RPS,RPS,field,normal,0,RPS,0,7,AM Rahane,Feroz Shah Kotla,C Shamshuddin,RJ Tucker,NaN
550,551,2016,Hyderabad,2016-05-06,GL,SRH,SRH,field,normal,0,SRH,0,5,B Kumar,"Rajiv Gandhi International Stadium, Uppal",M Erasmus,S Ravi,NaN
551,552,2016,Bangalore,2016-05-07,RPS,RCB,RCB,field,normal,0,RCB,0,7,V Kohli,M Chinnaswamy Stadium,CB Gaffaney,BNJ Oxenford,NaN
552,553,2016,Chandigarh,2016-05-07,KIXP,DD,DD,field,normal,0,KIXP,9,0,MP Stoinis,"Punjab Cricket Association IS Bindra Stadium, ...",HDPK Dharmasena,CK Nandan,NaN
553,554,2016,Visakhapatnam,2016-05-08,SRH,MI,MI,field,normal,0,SRH,85,0,A Nehra,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,S Ravi,C Shamshuddin,NaN
554,555,2016,Kolkata,2016-05-08,KKR,GL,GL,field,normal,0,GL,0,5,P Kumar,Eden Gardens,M Erasmus,RJ Tucker,NaN
555,556,2016,Chandigarh,2016-05-09,RCB,KIXP,KIXP,field,normal,0,RCB,1,0,SR Watson,"Punjab Cricket Association IS Bindra Stadium, ...",AK Chaudhary,HDPK Dharmasena,NaN
556,557,2016,Visakhapatnam,2016-05-10,SRH,RPS,SRH,bat,normal,0,SRH,4,0,A Zampa,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,CB Gaffaney,VK Sharma,NaN
557,558,2016,Bangalore,2016-05-11,RCB,MI,MI,field,normal,0,MI,0,6,KH Pandya,M Chinnaswamy Stadium,AY Dandekar,C Shamshuddin,NaN
558,559,2016,Hyderabad,2016-05-12,SRH,DD,DD,field,normal,0,DD,0,7,CH Morris,"Rajiv Gandhi International Stadium, Uppal",K Bharatan,M Erasmus,NaN
559,560,2016,Visakhapatnam,2016-05-13,MI,KIXP,MI,bat,normal,0,KIXP,0,7,MP Stoinis,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,HDPK Dharmasena,CK Nandan,NaN
560,561,2016,Bangalore,2016-05-14,RCB,GL,GL,field,normal,0,RCB,144,0,AB de Villiers,M Chinnaswamy Stadium,AY Dandekar,VK Sharma,NaN
561,562,2016,Kolkata,2016-05-14,RPS,KKR,RPS,bat,normal,1,KKR,0,8,YK Pathan,Eden Gardens,A Nand Kishore,BNJ Oxenford,NaN
562,563,2016,Chandigarh,2016-05-15,KIXP,SRH,KIXP,bat,normal,0,SRH,0,7,HM Amla,"Punjab Cricket Association IS Bindra Stadium, ...",KN Ananthapadmanabhan,M Erasmus,NaN
563,564,2016,Visakhapatnam,2016-05-15,MI,DD,DD,field,normal,0,MI,80,0,KH Pandya,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Nitin Menon,CK Nandan,NaN
564,565,2016,Kolkata,2016-05-16,KKR,RCB,RCB,field,normal,0,RCB,0,9,V Kohli,Eden Gardens,CB Gaffaney,A Nand Kishore,NaN
565,566,2016,Visakhapatnam,2016-05-17,DD,RPS,RPS,field,normal,1,RPS,19,0,AB Dinda,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Nitin Menon,C Shamshuddin,NaN
566,567,2016,Bangalore,2016-05-18,RCB,KIXP,KIXP,field,normal,1,RCB,82,0,V Kohli,M Chinnaswamy Stadium,KN Ananthapadmanabhan,M Erasmus,NaN
567,568,2016,Kanpur,2016-05-19,KKR,GL,GL,field,normal,0,GL,0,6,DR Smith,Green Park,AK Chaudhary,CK Nandan,NaN
568,569,2016,Raipur,2016-05-20,SRH,DD,DD,field,normal,0,DD,0,6,KK Nair,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
569,570,2016,Visakhapatnam,2016-05-21,KIXP,RPS,KIXP,bat,normal,0,RPS,0,4,MS Dhoni,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,HDPK Dharmasena,Nitin Menon,NaN
570,571,2016,Kanpur,2016-05-21,MI,GL,GL,field,normal,0,GL,0,6,SK Raina,Green Park,AK Chaudhary,CK Nandan,NaN
571,572,2016,Kolkata,2016-05-22,KKR,SRH,SRH,field,normal,0,KKR,22,0,YK Pathan,Eden Gardens,KN Ananthapadmanabhan,M Erasmus,NaN
572,573,2016,Raipur,2016-05-22,DD,RCB,RCB,field,normal,0,RCB,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
573,574,2016,Bangalore,2016-05-24,GL,RCB,RCB,field,normal,0,RCB,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
574,575,2016,Delhi,2016-05-25,SRH,KKR,KKR,field,normal,0,SRH,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
575,576,2016,Delhi,2016-05-27,GL,SRH,SRH,field,normal,0,SRH,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
576,577,2016,Bangalore,2016-05-29,SRH,RCB,SRH,bat,normal,0,SRH,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [62]:
# 8. Find out in which stadium the maximum number of matches have been played and in which stadium minimum? 
# What is the highest and the lowest number? Show the code.
df = pd.DataFrame(matches)
matches_venue = df.groupby('venue').venue.count()
matches_venue

venue
Barabati Stadium                                         7
Brabourne Stadium                                       11
Buffalo Park                                             3
De Beers Diamond Oval                                    3
Dr DY Patil Sports Academy                              17
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     11
Dubai International Cricket Stadium                      7
Eden Gardens                                            54
Feroz Shah Kotla                                        53
Green Park                                               2
Himachal Pradesh Cricket Association Stadium             9
Holkar Cricket Stadium                                   2
JSCA International Stadium Complex                       7
Kingsmead                                               15
M Chinnaswamy Stadium                                   58
MA Chidambaram Stadium, Chepauk                         48
Maharashtra Cricket Association Stadium                  8
Nehru Stadium                                            5
New Wanderers Stadium                                    8
Newlands                                                 7
OUTsurance Oval                                          2
Punjab Cricket Association IS Bindra Stadium, Mohali     7
Punjab Cricket Association Stadium, Mohali              35
Rajiv Gandhi International Stadium, Uppal               41
Sardar Patel Stadium, Motera                            12
Saurashtra Cricket Association Stadium                   5
Sawai Mansingh Stadium                                  33
Shaheed Veer Narayan Singh International Stadium         6
Sharjah Cricket Stadium                                  6
Sheikh Zayed Stadium                                     7
St George's Park                                         7
Subrata Roy Sahara Stadium                              17
SuperSport Park                                         12
Vidarbha Cricket Association Stadium, Jamtha             3
Wankhede Stadium                                        49
Name: venue, dtype: int64

In [71]:
# max and min

print(matches_venue.max())
print(matches_venue.min())

58
2

In [82]:
# 9. The following dataframe contains large blocks of NaNs. 
# Fill the NAs with mean only for 2 or less consecutive values of NAs. 
# Refer to the documentation of fillna() to find out the parameter you would use to fill only a certail number of NAs.
# The resulting dataframe should look like df_filled shown below.

df = pd.DataFrame({'val1':[4,np.nan,7,np.nan,np.nan,9,5, np.nan , 1,9,np.nan, np.nan,np.nan, 5, np.nan], 
                    'val2': [ np.nan, 5,7,np.nan, np.nan,8,3,np.nan, 4,np.nan, np.nan, np.nan,np.nan,21,np.nan]})

d = {'val1': {0: 4.0,1: 5.7142857142857144,2: 7.0,3: 5.7142857142857144,4: np.nan,5: 9.0,6: 5.0,7: np.nan,8: 1.0,9: 9.0,10: np.nan,11: np.nan,12: np.nan,13: 5.0,14: np.nan},
'val2': {0: 8.0,1: 5.0,2: 7.0,3: 8.0,4: np.nan,5: 8.0,6: 3.0,7: np.nan,8: 4.0,9: np.nan,10: np.nan,11: np.nan,12: np.nan,13: 21.0,14: np.nan}}

df_filled = pd.DataFrame(d)

df = df.fillna(df.mean(),limit=2)
df

        val1  val2
0   4.000000   8.0
1   5.714286   5.0
2   7.000000   7.0
3   5.714286   8.0
4        NaN   NaN
5   9.000000   8.0
6   5.000000   3.0
7        NaN   NaN
8   1.000000   4.0
9   9.000000   NaN
10       NaN   NaN
11       NaN   NaN
12       NaN   NaN
13  5.000000  21.0
14       NaN   NaN

In [80]:
# 10. For the dataframe given below, 
# Convert the NaN values to zero
# Add a row called diff with the difference between minimum and maximum value in each column. Try solving it using lambda function
# Add a column called diff with the difference between minimum and maximum value in each row. 
# The final df should look like df_final shown below

df = pd.DataFrame({'val1':[9,15,71,9,5], 'val2': [8,31,10, 14,np.nan]})

df_final = pd.DataFrame({'diff': {0: 1.0, 1: -16.0, 2: 61.0, 3: -5.0, 4: 5.0, 'diff': 35.0},
 'val1': {0: 9.0, 1: 15.0, 2: 71.0, 3: 9.0, 4: 5.0, 'diff': 66.0},
 'val2': {0: 8.0, 1: 31.0, 2: 10.0, 3: 14.0, 4: 0.0, 'diff': 31.0}})

df = df.fillna(0)

df['diff'] = (df['val1'] - df['val2'])

df

   val1  val2  diff
0     9   8.0   1.0
1    15  31.0 -16.0
2    71  10.0  61.0
3     9  14.0  -5.0
4     5   0.0   5.0